let @a = "printf(\"[Shaun_Debug %s-%s,%s,%d]\\n\", __DATE__, __TIME__, __func__, __LINE__);\n"
      \. "\n"
let @b = "u32retCode = function_name;\n"
      \. "if (u32retCode != TRUE)\n"
      \. "{\n"
      \. "    printf(\"[Shaun_Debug %s,%d]Fail to call function_name. Return Code:%u\\n\", __func__, __LINE__, u32retCode);\n"
      \. "    return FALSE;\n"
      \. "}\n"
      \. "\n"
